// pages/calc/calc.js

const util = require("../../utils/util")

Page({
    data: {
        inputHistoryStr:'',
        current:'0',
        dot:'',
        flag_dot:'false',/**用于判断是否已经加过'.' */
    },
    clear:function(){
        this.setData({
            inputHistoryStr:'',
            current:'0',
            flag_dot:'false'
        })
    },
    ClearError:function(){
        this.setData({
            current:'0'
        })
    },
    input1:function(){
        if(this.data.current=='0'){
            this.setData({
                current:'1'
            })
        }
        else{
            this.setData({
                current:this.data.current+'1'
            })
            console.log(this.data.current)
        }
    },
    input2:function(){
        if(this.data.current=='0'){
            this.setData({
                current:'2'
            })
        }
        else{
            this.setData({
                current:this.data.current+'2'
            })
        }
    },
    input3:function(){
        if(this.data.current=='0'){
            this.setData({
                current:'3'
            })
        }
        else{
            this.setData({
                current:this.data.current+'3'
            })
        }
    },
    input4:function(){
        if(this.data.current=='0'){
            this.setData({
                current:'4'
            })
        }
        else{
            this.setData({
                current:this.data.current+'4'
            })
        }
    },
    input5:function(){
        if(this.data.current=='0'){
            this.setData({
                current:'5'
            })
        }
        else{
            this.setData({
                current:this.data.current+'5'
            })
        }
    },
    input6:function(){
        if(this.data.current=='0'){
            this.setData({
                current:'6'
            })
        }
        else{
            this.setData({
                current:this.data.current+'6'
            })
        }
    },
    input7:function(){
        if(this.data.current=='0'){
            this.setData({
                current:'7'
            })
        }
        else{
            this.setData({
                current:this.data.current+'7'
            })
        }
    },
    input8:function(){
        if(this.data.current=='0'){
            this.setData({
                current:'8'
            })
        }
        else{
            this.setData({
                current:this.data.current+'8'
            })
        }
    },
    input9:function(){
        if(this.data.current=='0'){
            this.setData({
                current:'9'
            })
        }
        else{
            this.setData({
                current:this.data.current+'9'
            })
        }
    },
    input0:function(){
        if(this.data.current=='0'){
            this.setData({
                current:'0'
            })
        }
        else{
            this.setData({
                current:this.data.current+'0'
            })
        }
    },
    dot:function(){
        if(this.data.current!='0'){
            this.setData({
                dot:'.'
            })
        }
        if(this.data.flag_dot=='false'){
            this.setData({
                flag_dot:'true',
                current:this.data.current+this.data.dot
            })
        }

    },
    repeat:function(){
        this.setData({
            inputHistoryStr:this.data.inputHistoryStr+this.data.current,
            current:'0'
        })
    },
    check:function(){/**检查当前输入字段末尾有无运算符，若有，输出false */
        let cur=toString(this.data.current)
        var lastWord=cur.charAt(cur.length-1)
        if(lastWord=='*'||lastWord=='/'||lastWord=='+'||lastWord=='-'){
            return false
        }
        return true
    },
    divide:function(){
        if(this.check()){
        this.setData({
            current:this.data.current+'/'
        })
    }
        else{
            this.backspace()
            this.setData({
                current:this.data.current+'/'
            })
        }
        this.repeat()
        this.setData({
            flag_dot:'false'
        })
    },
    multiply:function(){
        if(this.check()){
            this.setData({
                current:this.data.current+'*'
            })
        }
        else{
            this.backspace()
            this.setData({
                current:this.data.current+'*'
            })
        }
        this.repeat()
        this.setData({
            flag_dot:'false'
        })
    },
    minus:function(){
        if(this.check()){
            this.setData({
                current:this.data.current+'-'
            })
        }
        else{
            this.backspace()
            this.setData({
                current:this.data.current+'-'
            })
        }
        this.repeat()
        this.setData({
            flag_dot:'false'
        })
    },
    add:function(){
        if(this.check()){
            this.setData({
                current:this.data.current+'+'
            })
        }
        else{
            this.backspace()
            this.setData({
                current:this.data.current+'+'
            })
        }
        this.repeat()
        this.setData({
            flag_dot:'false'
        })
    },
    backspace:function(){
        let cur=this.data.current.toString()
        this.setData({
            current:cur.substring(0,cur.length-1)
        })
        if(this.data.current==''){
            this.setData({
                current:'0'
            })
        }
    },
    negate:function(){
        let cur=this.data.current
        if(parseFloat(cur)+parseFloat(Math.abs(cur))==0){
            this.setData({
                current:Math.abs(cur)
            })
        }
        else{
            this.setData({
                current:'-'+cur
            })
        }
    },
    equal:function(){
        this.repeat()
        this.setData({
            current:util.calcExpression(this.data.inputHistoryStr)/**eval函数被禁用！ */,
            inputHistoryStr:'',
            flag_dot:'false'
        })
    }
})